import { User, Restaurant, FoodItem, Order, Feedback } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_cust_1',
    name: 'Maknoon Sultana',
    email: 'customer@quickbite.com',
    password: 'password123',
    role: 'CUSTOMER',
    phone: '+880 1711-223344',
    address: 'House 42, Road 11, Dhanmondi, Dhaka',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_rest_1',
    name: 'Chef Kabir Ahmed',
    email: 'manager@quickbite.com',
    password: 'password123',
    role: 'RESTAURANT_MANAGER',
    phone: '+880 1819-556677',
    address: 'Gulshan 2, Dhaka',
    avatar: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=150&auto=format&fit=crop&q=80',
    restaurantId: 'rest_1',
  },
  {
    id: 'user_deliv_1',
    name: 'Rakibul Hasan',
    email: 'delivery@quickbite.com',
    password: 'password123',
    role: 'DELIVERY_PERSON',
    phone: '+880 1912-334455',
    address: 'Mohakhali, Dhaka',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_admin_1',
    name: 'Dr. Nazia Majadi (Admin)',
    email: 'admin@quickbite.com',
    password: 'password123',
    role: 'ADMIN',
    phone: '+880 1700-000000',
    address: 'NSTU Campus, Noakhali',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest_1',
    name: 'Royal Biryani House',
    description: 'Authentic Kachchi Biryani slow-cooked with aromatic basmati rice, tender mutton & roasted potatoes.',
    email: 'royalbiryani@quickbite.com',
    phone: '+880 1711-987654',
    address: 'Old Dhaka Heritage Lane, Nazira Bazar',
    cuisine: 'Biryani & Mughal',
    rating: 4.8,
    ratingCount: 342,
    deliveryTime: '20-30 min',
    deliveryFee: 40,
    minOrder: 200,
    bannerImage: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=200&auto=format&fit=crop&q=80',
    isApproved: true,
    isOpen: true,
    ownerId: 'user_rest_1',
  },
  {
    id: 'rest_2',
    name: 'Smash Burger Lab',
    description: 'Crispy double-smashed beef patties, melted gouda, caramelized onions and signature secret sauce.',
    email: 'smashburger@quickbite.com',
    phone: '+880 1822-112233',
    address: 'Banani 11, Dhaka',
    cuisine: 'Burgers & Fast Food',
    rating: 4.7,
    ratingCount: 512,
    deliveryTime: '25-35 min',
    deliveryFee: 45,
    minOrder: 250,
    bannerImage: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200&auto=format&fit=crop&q=80',
    isApproved: true,
    isOpen: true,
    ownerId: 'user_rest_2',
  },
  {
    id: 'rest_3',
    name: 'Bella Italia Woodfire',
    description: 'Artisan Neapolitan pizzas hand-stretched and baked in wood-fired stone oven with San Marzano tomatoes.',
    email: 'bellaitalia@quickbite.com',
    phone: '+880 1933-445566',
    address: 'Gulshan Avenue, Dhaka',
    cuisine: 'Italian & Pizza',
    rating: 4.9,
    ratingCount: 280,
    deliveryTime: '30-40 min',
    deliveryFee: 50,
    minOrder: 350,
    bannerImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=200&auto=format&fit=crop&q=80',
    isApproved: true,
    isOpen: true,
    ownerId: 'user_rest_3',
  },
  {
    id: 'rest_4',
    name: 'Tokyo Ramen & Sushi Bar',
    description: 'Rich 16-hour Tonkotsu broth, handcrafted noodles, fresh salmon sashimi, and crispy tempura rolls.',
    email: 'tokyoramen@quickbite.com',
    phone: '+880 1744-889900',
    address: 'Uttara Sector 3, Dhaka',
    cuisine: 'Japanese & Asian',
    rating: 4.6,
    ratingCount: 195,
    deliveryTime: '35-45 min',
    deliveryFee: 50,
    minOrder: 300,
    bannerImage: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=200&auto=format&fit=crop&q=80',
    isApproved: true,
    isOpen: true,
    ownerId: 'user_rest_4',
  },
  {
    id: 'rest_5',
    name: 'Sweet Treats & Gelato Cafe',
    description: 'Decadent Belgian waffles, dark chocolate lava cakes, artisan iced lattes and creamy gelato.',
    email: 'sweettreats@quickbite.com',
    phone: '+880 1655-778899',
    address: 'Dhanmondi 27, Dhaka',
    cuisine: 'Desserts & Cafe',
    rating: 4.9,
    ratingCount: 420,
    deliveryTime: '15-25 min',
    deliveryFee: 35,
    minOrder: 150,
    bannerImage: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=200&auto=format&fit=crop&q=80',
    isApproved: true,
    isOpen: true,
    ownerId: 'user_rest_5',
  }
];

export const INITIAL_FOOD_ITEMS: FoodItem[] = [
  // Royal Biryani
  {
    id: 'food_101',
    restaurantId: 'rest_1',
    name: 'Grand Special Mutton Kacchi Biryani',
    description: 'Tender marinated baby mutton with aromatic Chinigura rice, golden potato, shahi boiled egg & borhani.',
    price: 380,
    category: 'Biryani Specials',
    isAvailable: true,
    isVeg: false,
    isSpicy: true,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    preparationTime: '15 min',
  },
  {
    id: 'food_102',
    restaurantId: 'rest_1',
    name: 'Shahi Chicken Roast with Polao',
    description: 'Rich almond and poppy seed gravy cooked whole chicken leg served with fragrant ghee polao.',
    price: 290,
    category: 'Biryani Specials',
    isAvailable: true,
    isVeg: false,
    isSpicy: false,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500&auto=format&fit=crop&q=80',
    rating: 4.7,
    preparationTime: '15 min',
  },
  {
    id: 'food_103',
    restaurantId: 'rest_1',
    name: 'Traditional Mint Borhani (500ml)',
    description: 'Refreshing yogurt drink spiced with roasted cumin, black salt, fresh mint and green chili.',
    price: 90,
    category: 'Beverages',
    isAvailable: true,
    isVeg: true,
    isSpicy: true,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    preparationTime: '5 min',
  },
  {
    id: 'food_104',
    restaurantId: 'rest_1',
    name: 'Shahi Jorda with Baby Sweet Sweets',
    description: 'Sweet saffron basmati rice topped with almonds, pistachios, raisins, and mini gulab jamuns.',
    price: 130,
    category: 'Desserts',
    isAvailable: true,
    isVeg: true,
    isSpicy: false,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    rating: 4.6,
    preparationTime: '5 min',
  },

  // Smash Burger Lab
  {
    id: 'food_201',
    restaurantId: 'rest_2',
    name: 'Double Truffle Smash Burger',
    description: 'Two 100% prime beef patties, white cheddar cheese, sautéed butter mushrooms and black truffle mayo.',
    price: 460,
    category: 'Smash Burgers',
    isAvailable: true,
    isVeg: false,
    isSpicy: false,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    preparationTime: '18 min',
  },
  {
    id: 'food_202',
    restaurantId: 'rest_2',
    name: 'Crispy Nashville Hot Chicken Burger',
    description: 'Buttermilk fried chicken breast drenched in cayenne oil, house slaw, dill pickles on brioche bun.',
    price: 390,
    category: 'Chicken Burgers',
    isAvailable: true,
    isVeg: false,
    isSpicy: true,
    image: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    preparationTime: '15 min',
  },
  {
    id: 'food_203',
    restaurantId: 'rest_2',
    name: 'Loaded Cheesy Cajun Fries',
    description: 'Crispy skin-on fries smothered in warm cheddar cheese sauce, jalapeño bits, and bacon crumble.',
    price: 220,
    category: 'Sides & Fries',
    isAvailable: true,
    isVeg: false,
    isSpicy: true,
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=500&auto=format&fit=crop&q=80',
    rating: 4.7,
    preparationTime: '10 min',
  },

  // Bella Italia
  {
    id: 'food_301',
    restaurantId: 'rest_3',
    name: 'Quattro Formaggi Woodfired Pizza (12")',
    description: 'Mozzarella di bufala, gorgonzola dolce, aged parmesan, and fontina with fresh basil drizzle.',
    price: 780,
    category: 'Artisan Pizzas',
    isAvailable: true,
    isVeg: true,
    isSpicy: false,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    preparationTime: '20 min',
  },
  {
    id: 'food_302',
    restaurantId: 'rest_3',
    name: 'Spicy Pepperoni & Hot Honey Pizza (12")',
    description: 'Handcrafted beef pepperoni, San Marzano tomato sauce, fresh mozzarella, finished with hot chili honey.',
    price: 850,
    category: 'Artisan Pizzas',
    isAvailable: true,
    isVeg: false,
    isSpicy: true,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    preparationTime: '20 min',
  },
  {
    id: 'food_303',
    restaurantId: 'rest_3',
    name: 'Creamy Fettuccine Alfredo con Funghi',
    description: 'Al dente fettuccine pasta tossed in rich parmesan cream, garlic butter, and wild porcini mushrooms.',
    price: 590,
    category: 'Handmade Pasta',
    isAvailable: true,
    isVeg: true,
    isSpicy: false,
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    preparationTime: '15 min',
  },

  // Tokyo Ramen
  {
    id: 'food_401',
    restaurantId: 'rest_4',
    name: 'Signature Tonkotsu Black Garlic Ramen',
    description: '16-hour simmered pork/beef broth, chashu slices, soft ajitsuke tamago egg, nori, and black garlic oil.',
    price: 620,
    category: 'Ramen Bowls',
    isAvailable: true,
    isVeg: false,
    isSpicy: false,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    preparationTime: '15 min',
  },
  {
    id: 'food_402',
    restaurantId: 'rest_4',
    name: 'Salmon Volcano Sushi Roll (8 pcs)',
    description: 'Fresh Norwegian salmon, cucumber, cream cheese topped with spicy flamed crab meat and unagi glaze.',
    price: 690,
    category: 'Sushi & Maki',
    isAvailable: true,
    isVeg: false,
    isSpicy: true,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=500&auto=format&fit=crop&q=80',
    rating: 4.8,
    preparationTime: '15 min',
  },

  // Sweet Treats
  {
    id: 'food_501',
    restaurantId: 'rest_5',
    name: 'Warm Belgian Chocolate Lava Cake',
    description: 'Molten Valrhona dark chocolate center served with Madagascar vanilla bean gelato and strawberry.',
    price: 320,
    category: 'Artisan Desserts',
    isAvailable: true,
    isVeg: true,
    isSpicy: false,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80',
    rating: 5.0,
    preparationTime: '12 min',
  },
  {
    id: 'food_502',
    restaurantId: 'rest_5',
    name: 'Caramel Biscoff Loaded Waffle',
    description: 'Fluffy golden Belgian waffle drizzled with Lotus Biscoff spread, crushed biscuits & whipped cream.',
    price: 360,
    category: 'Artisan Desserts',
    isAvailable: true,
    isVeg: true,
    isSpicy: false,
    image: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=500&auto=format&fit=crop&q=80',
    rating: 4.9,
    preparationTime: '10 min',
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'order_1001',
    orderNumber: 'QB-8921',
    customerId: 'user_cust_1',
    customerName: 'Maknoon Sultana',
    customerEmail: 'customer@quickbite.com',
    customerPhone: '+880 1711-223344',
    deliveryAddress: 'House 42, Road 11, Dhanmondi, Dhaka',
    restaurantId: 'rest_1',
    restaurantName: 'Royal Biryani House',
    restaurantAddress: 'Old Dhaka Heritage Lane, Nazira Bazar',
    deliveryPersonId: 'user_deliv_1',
    deliveryPersonName: 'Rakibul Hasan',
    deliveryPersonPhone: '+880 1912-334455',
    items: [
      {
        id: 'oi_1',
        orderId: 'order_1001',
        foodItemId: 'food_101',
        name: 'Grand Special Mutton Kacchi Biryani',
        price: 380,
        quantity: 2,
        subtotal: 760,
      },
      {
        id: 'oi_2',
        orderId: 'order_1001',
        foodItemId: 'food_103',
        name: 'Traditional Mint Borhani (500ml)',
        price: 90,
        quantity: 2,
        subtotal: 180,
      }
    ],
    subtotal: 940,
    deliveryFee: 40,
    tax: 47,
    discount: 50,
    totalAmount: 977,
    status: 'OUT_FOR_DELIVERY',
    paymentMethod: 'BKASH',
    paymentStatus: 'COMPLETED',
    transactionId: 'TRX_BKASH_99812A',
    notes: 'Please ring the bell twice and bring extra spoons.',
    estimatedDeliveryTime: '12-15 mins',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'order_1002',
    orderNumber: 'QB-8922',
    customerId: 'user_cust_1',
    customerName: 'Maknoon Sultana',
    customerEmail: 'customer@quickbite.com',
    customerPhone: '+880 1711-223344',
    deliveryAddress: 'House 42, Road 11, Dhanmondi, Dhaka',
    restaurantId: 'rest_2',
    restaurantName: 'Smash Burger Lab',
    restaurantAddress: 'Banani 11, Dhaka',
    items: [
      {
        id: 'oi_3',
        orderId: 'order_1002',
        foodItemId: 'food_201',
        name: 'Double Truffle Smash Burger',
        price: 460,
        quantity: 1,
        subtotal: 460,
      },
      {
        id: 'oi_4',
        orderId: 'order_1002',
        foodItemId: 'food_203',
        name: 'Loaded Cheesy Cajun Fries',
        price: 220,
        quantity: 1,
        subtotal: 220,
      }
    ],
    subtotal: 680,
    deliveryFee: 45,
    tax: 34,
    discount: 0,
    totalAmount: 759,
    status: 'PREPARING',
    paymentMethod: 'CARD',
    paymentStatus: 'COMPLETED',
    transactionId: 'TRX_VISA_448102',
    estimatedDeliveryTime: '25-30 mins',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  }
];

export const INITIAL_FEEDBACKS: Feedback[] = [
  {
    id: 'fb_1',
    orderId: 'order_1001',
    customerId: 'user_cust_1',
    customerName: 'Maknoon Sultana',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    restaurantId: 'rest_1',
    restaurantName: 'Royal Biryani House',
    rating: 5,
    comment: 'The kacchi was extraordinarily fragrant, warm and soft! Delivery reached in just 22 minutes.',
    createdAt: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
  },
  {
    id: 'fb_2',
    orderId: 'order_998',
    customerId: 'user_cust_2',
    customerName: 'Umme Nur Sadia',
    customerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    restaurantId: 'rest_3',
    restaurantName: 'Bella Italia Woodfire',
    rating: 5,
    comment: 'Best authentic sourdough crust in Dhaka! The hot honey pepperoni is unmatched.',
    createdAt: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
  }
];
